name: pre-commit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: "**/*.py"

      - name: List changed files
        run: |
          echo "files: ${{ steps.changed-files.outputs.all_changed_files }}:::"        

      - run: python -m pip install pre-commit
        shell: bash

      - run: python -m pip freeze --local
        shell: bash

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - run: pre-commit run -v --files ${{ steps.changed-files.outputs.all_changed_files }}